version: '3'

services:
  blog_dev:
    image: postgres
    container_name: blog_dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog_dev
    volumes:
      - pg:/data/postgres

volumes:
  pg:
    driver: local
